version: '3'
services:
  mysql:
    image: mariadb:latest
    logging:
      driver: none
    command: --max_allowed_packet=256M
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
       - 33067:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    logging:
      driver: none
    env_file:
      - .env
    volumes:
        - ./lsws/conf:/usr/local/lsws/conf
        - ./lsws/admin-conf:/usr/local/lsws/admin/conf
        - ./bin/container:/usr/local/bin
        - ./sites:/var/www/vhosts/
        - ./acme:/root/.acme.sh/
        - ./logs:/usr/local/lsws/logs/
    ports:
      - 8077:80
      - 44377:443
      - 44378:443/udp
      - 7087:7080
    restart: always
    environment:
      TZ: ${TimeZone}
#  phpmyadmin:
#    image: bitnami/phpmyadmin:5.0.2-debian-10-r72
#    logging:
#      driver: none
#    ports:
#      - 8080:80
#      - 8443:443
#    environment:
#        DATABASE_HOST: mysql
#    restart: always    
